config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index', as: 'notifications'
  get '/notification/:id/:room_id', to: 'notifications#mark_read', as: 'mark_notification_read'
  resources :rooms do
    resources :messages
  end
  get 'main/index'
  devise_for :users, :controllers => { registrations: 'users/registrations' }

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  get '/users/:id', to: 'users#show', as: 'user'
  root 'main#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  after_create_commit { broadcast_append_to self.room }
  before_create :confirm_participant
  after_create_commit :notify_recipient
  
  def notify_recipient
    recipient = notification_participant
    MessageNotification.with(message: self, user_id: self.user_id).deliver(recipient)
  end

  def notification_participant
    self.room.participants.where.not(user_id: self.user_id).first.user
  end

  def confirm_participant
    if self.room.is_private
      is_participant = Participant.where(user_id: self.user.id, room_id: self.room.id).first
      throw :abort unless is_participant
    end
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  include Noticed::Model
  belongs_to :recipient, polymorphic: true
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
    validates_uniqueness_of :name
    has_many :messages
    has_many :participants, dependent: :destroy

    def self.create_private_room(users, room_name)
        single_room = Room.create(name: room_name)
        users.each do |user|
          Participant.create(user_id: user.id, room_id: single_room.id )
        end
        single_room
      end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :messages
  has_many :notifications, as: :recipient

  validates_uniqueness_of :username

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  scope :all_except, ->(user) { where.not(id: user) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :get_current_user
    def create
        @message = @current_user.messages.create(content: msg_params[:content], room_id: params[:room_id])
    end
    
    private
    def get_current_user
        @current_user = current_user
    end

    def msg_params
        params.require(:message).permit(:content)
    end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = current_user.notifications.unread.uniq { |n| n.params[:user_id] }
  end

  def mark_read
    notifications = current_user.notifications.unread.find_all {|n| n.params[:user_id] == params[:id].to_i  }
    return if notifications.empty?

    notifications.each do |n|
      n.mark_as_read!
    end
    message = Room.find(params[:room_id]).messages.last
    redirect_to user_path(notifications.first.params[:message].user.id, anchor: "#message_#{message.id}")
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_users

  def index
    redirect_to '/signin' unless @current_user
  end

  def show
    @message = Message.new
    @single_room = Room.find(params[:id])
    @messages = @single_room.messages
    @room = Room.new

    render "index"
  end

  private

  def set_users
    @current_user = current_user
    @users = User.all_except(@current_user)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        redirect_to root_path
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        redirect_to root_path
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      redirect_to root_path
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name, :username])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @current_user = current_user
    @users = User.all_except(@current_user)
    @room = Room.new
    @message = Message.new
    @room_name = get_name(@user, @current_user)
    @single_room = Room.where(name: @room_name).first || Room.create_private_room([@user, @current_user], @room_name)
    @messages = @single_room.messages

    render "rooms/index"
  end

  private
  def get_name(user1, user2)
    users = [user1, user2].sort
    "private_#{users[0].id}_#{users[1].id}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="flex justify-between py-6 w-full lg:px-48 md:px-12 px-4 content-center bg-secondary z-10">
    <div class="flex items-center">
        <a href="/main/index" class="bg-black text-white font-bold text-xl p-4">Chat</a>
    </div>
    <div class="font-montserrat hidden md:block">
        <button class="mr-6">
            Hi, <strong><%= current_user.full_name %></strong>
        </button>
        <button type="button" class="inline-flex items-center px-5 py-2.5 text-sm font-medium text-center text-white bg-black rounded-3xl hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
            <%= link_to "Notifications", notifications_path, :class => 'navbar-link'  %>
            <span class="inline-flex justify-center items-center ml-2 w-4 h-4 text-xs font-semibold text-blue-800 bg-blue-200 rounded-full">
            <%= current_user.notifications.unread.uniq { |n| n.params[:user_id] }.count %>
            </span>
        </button>
        <button class="py-2 px-4 text-white bg-black rounded-3xl">
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        </button>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Chatting App</title>
  <link rel="stylesheet" href="dist/styles.css" />
  <script src="dist/script.js"></script>
</head>

<body>
  <!-- Navigation -->
  <nav class="flex justify-between py-6 w-full lg:px-48 md:px-12 px-4 content-center bg-secondary z-10">
    <div class="flex items-center">
        <a href="" class="bg-black text-white font-bold text-xl p-4">Chat</a>
    </div>
    <% if user_signed_in? %>
      <button class="py-2 px-4 text-white bg-black rounded-3xl">
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      </button>
    <% else %>
      <div class="font-montserrat hidden md:block">
        <button class="mr-6">
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        </button>
        <button class="py-2 px-4 text-white bg-black rounded-3xl">
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
        </button>
      </div>
    <% end %>
  </nav>

  <!-- Hero -->
  <section
    class=" md:mt-0 md:h-screen flex flex-col justify-center text-center md:text-left md:flex-row md:justify-between md:items-center lg:px-48 md:px-12 px-4 bg-secondary">
    <div class="md:flex-1 md:mr-10">
      <h1 class="font-pt-serif text-5xl font-bold mb-7">
        Chat easily and securely
        <span class="bg-underline1 bg-left-bottom bg-no-repeat pb-2 bg-100%">
          with anyone.
        </span>
      </h1>
      <p class="font-pt-serif font-normal mb-7">
        A new way to meet and chat with people.
      </p>
      <% if user_signed_in? %>
        <div class="font-montserrat">
          <button class="bg-black px-6 py-4 rounded-lg border-2 border-black border-solid text-white mr-2 mb-2">
            <%= link_to "Chat Now", rooms_path, :class => 'navbar-link'  %>
          </button>
        </div>
      <% end %>
    </div>
    <div class="flex justify-around md:block mt-8 md:mt-0 md:flex-1">
      
      <img src="<%= asset_path('chatting-people.jpeg') %>" class="h-50" />
      
    </div>
  </section>
</body>

</html>

app/views/messages/_message.html.erb
 <% unless message.nil? %>
    <div id="message_<%= message.id%>" class="px-2">
        <div class="w-fit max-w-[40%] p-5 rounded-[12px] mb-5 bg-indigo-50 text-black" >
            <p class = "text-sm font-light text-gray-500"><%= message.user.username%></p> 
            <%= message.content %>
        </div>
    </div>
<% end %>

app/views/notifications/index.html.erb
<body>
  
  <%= render "layouts/navbar", current_user: current_user %>
  <body class="bg-white font-family-karla h-screen items-center text-center">
    <h1><strong> Notifications </strong></h1><br>
    <div class="w-full flex flex-wrap">

        <div class="w-full h-screen flex flex-col items-center text-center bg-slate-200">
          <div>
            <% if @notifications.present? %>
                <% @notifications.each do |notification| %>
                    <br>
                    <div id="toast-simple" class="flex items-center w-full max-w-s p-4 space-x-4 text-gray-500 bg-white divide-x divide-gray-200 rounded-lg shadow dark:text-gray-400 dark:divide-gray-700 space-x dark:bg-gray-800" role="alert">
                        <svg class="w-5 h-5 text-blue-600 dark:text-blue-500" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="paper-plane" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M511.6 36.86l-64 415.1c-1.5 9.734-7.375 18.22-15.97 23.05c-4.844 2.719-10.27 4.097-15.68 4.097c-4.188 0-8.319-.8154-12.29-2.472l-122.6-51.1l-50.86 76.29C226.3 508.5 219.8 512 212.8 512C201.3 512 192 502.7 192 491.2v-96.18c0-7.115 2.372-14.03 6.742-19.64L416 96l-293.7 264.3L19.69 317.5C8.438 312.8 .8125 302.2 .0625 289.1s5.469-23.72 16.06-29.77l448-255.1c10.69-6.109 23.88-5.547 34 1.406S513.5 24.72 511.6 36.86z"></path></svg>
                        <div class="pl-4 text-sm font-normal">You have a new message from <%= notification.params[:message].user.username %></div>
                        <div class="pl-4 text-sm font-normal">
                            <%= link_to "Read", mark_notification_read_path(notification.params[:message].user.id, notification.params[:message].room_id), :class => 'navbar-link'  %>
                        </div>
                    </div>
                <% end %>
            <% else %>
                No Notifications right now.
            <% end %>
          </div>
        </div>
    </div>

  </body>
</body>

app/views/rooms/_users.html.erb
<% users.each do |user| %>
    <div class = "px-5 text-left mt-2 text-blue-400">
        <%= link_to user.username, user %>
    </div>
<% end %>

app/views/rooms/index.html.erb
<body>
  
  <%= render "layouts/navbar", current_user: current_user %>
  <body class="bg-white font-family-karla h-screen">

    <div class="w-full flex flex-wrap">

        <div class="w-full md:w-1/4 flex flex-col text-center bg-slate-200">
          <h1><strong> Users </strong></h1>
          <div>
            <%= render "rooms/users", users: @users %>
          </div>
        </div>

        <div class="w-3/4 shadow-2xl h-full bg-slate-800 text-gray-100">
            <% if @single_room %>
              <%= turbo_stream_from @single_room %>
              <div id="messages", class = "mb-13 pb-7">
                <h4 class="text-center"> <%= @user&.username  %> </h4>
                <%= render @messages %>
              </div>
              <div class="form-group w-8/12 fixed bottom-0">
                <%= form_with(model: [@single_room ,@message], remote: true, class: "d-flex" ) do |f| %>
                  <%= f.text_field :content, id: 'chat-text', class: "form-control w-10/12 mr-5 text-black	", autocomplete: 'off' %>
                  <button class="rounded-full bg-blue-100 text-black p-3"><%= f.submit "Send" %></button>
                <% end %>
              </div>
            <% end %>
        </div>
    </div>

  </body>
</body>